# Generated by Django 6.0.6 on 2026-07-28 09:43

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0003_2_11'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='poker, tm, pushit…', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField(help_text="Racine de l'API de l'app, ex. https://poker-api.foxugly.com")),
                ('entitlement_path', models.CharField(default='/api/billing/entitlement/', help_text='Chemin du endpoint qui reçoit les droits poussés.', max_length=200)),
                ('shared_secret', models.CharField(default=core.models.generate_shared_secret, max_length=100)),
                ('active', models.BooleanField(default=True, help_text="Décoché : plus aucune livraison n'est émise.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, help_text='Statut Stripe brut', max_length=32)),
                ('plan_code', models.CharField(blank=True, max_length=50)),
                ('interval', models.CharField(blank=True, max_length=16)),
                ('quotas', models.JSONField(default=dict)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('grace_until', models.DateTimeField(blank=True, help_text='Fin de la période de grâce après un échec de paiement (§6.6)', null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(choices=[('stripe', 'Stripe'), ('manual', 'Manuel'), ('bypass', 'Bypass')], default='stripe', max_length=16)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='core.app')),
            ],
            options={
                'ordering': ('app', 'external_user_id'),
            },
        ),
        migrations.CreateModel(
            name='EntitlementDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('delivered', 'Livré'), ('failed', 'Échec')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.entitlement')),
            ],
            options={
                'verbose_name_plural': 'entitlement deliveries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="team1, team5… l'identifiant utilisé par l'app", max_length=50)),
                ('name', models.CharField(help_text='Libellé interne (admin), pas la vitrine client.', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quotas', models.JSONField(default=dict, help_text='Poussé tel quel à l\'app, ex. {"teams": 1}')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('public', models.BooleanField(default=True, help_text="Décoché : masqué du catalogue de l'app.")),
                ('active', models.BooleanField(default=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.app')),
                ('price_monthly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='djstripe.price')),
                ('price_yearly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='djstripe.price')),
            ],
            options={
                'ordering': ('app', 'sort_order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='AppCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.app')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='djstripe.customer')),
            ],
            options={
                'ordering': ('email',),
                'constraints': [models.UniqueConstraint(fields=('app', 'external_user_id'), name='unique_customer_per_app_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(fields=('app', 'external_user_id'), name='unique_entitlement_per_app_user'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('app', 'code'), name='unique_plan_code_per_app'),
        ),
    ]
