# Generated by Django 6.0.6 on 2026-07-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='previous_shared_secret',
            field=models.CharField(blank=True, help_text='Accepté pendant 24 h après une rotation.', max_length=100),
        ),
        migrations.AddField(
            model_name='app',
            name='secret_rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
