# Generated by Django 6.0.6 on 2026-07-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_app_previous_shared_secret_app_secret_rotated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='per_unit_quota_key',
            field=models.CharField(blank=True, help_text="Si renseigné, le quota de cette clé suit la QUANTITÉ souscrite au lieu d'être fixe : 3 exemplaires d'un plan à 2 €/app donnent 3 applications. Laisser vide pour un plan forfaitaire.", max_length=50),
        ),
    ]
