# Generated by Django 6.0.6 on 2026-07-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plan_per_unit_quota_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveIntegerField(default=0, help_text="Jours d'essai offerts à la première souscription. 0 = aucun essai. L'essai n'est accordé qu'une fois par client et pour une quantité de 1."),
        ),
    ]
