# Generated by Django 6.0.6 on 2026-07-29 16:04
#
# Le défaut seul change : les lignes existantes ne sont volontairement PAS
# réécrites. Les deux apps de production (poker, pushit) portent déjà le chemin
# canonique, et réécrire à l'aveugle couperait une app qui servirait encore
# l'ancien chemin — la vérification se fait au cas par cas avec le bouton
# « tester » de la console (ping signé, OPERATIONS.md §3.18).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plan_trial_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='entitlement_path',
            field=models.CharField(default='/api/v1/billing/entitlement/', help_text="Chemin du endpoint qui reçoit les droits poussés. Toute la flotte sert ses APIs sous /api/v1/ (OPERATIONS.md §3.18) : un chemin legacy ici casse en silence, car l'alias transitoire ne couvre pas les endpoints signés.", max_length=200),
        ),
    ]
